name: Bookie
options:
  bundleIdPrefix: com.bookie
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "16.2"
packages:
  Swinject:
    url: https://github.com/Swinject/Swinject.git
    version: 2.9.1
  CombineMoya:
    url: https://github.com/Moya/Moya
    version: 15.0.3
  Then:
    url: https://github.com/devxoul/Then
    version: 3.0.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    version: 5.7.1
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    version: 8.2.0
  SwifterSwift:
    url: https://github.com/SwifterSwift/SwifterSwift
    version: 7.0.0
  Reusable:
    url: https://github.com/AliSoftware/Reusable
    version: 4.1.2
  SHSearchBar:
    url: https://github.com/Blackjacx/SHSearchBar
    version: 2.1.0
  DifferenceKit:
    url: https://github.com/ra1028/DifferenceKit
    version: 1.3.0
targets:
  BookieApp:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: application
    platform: iOS
    sources: [Bookie]
    dependencies:
      - package: Swinject
      - package: CombineMoya
      - package: Then
      - package: SnapKit
      - package: Kingfisher
      - package: SwifterSwift
      - package: Reusable
      - package: SHSearchBar
      - package: DifferenceKit
    info:
      path: Bookie/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: YES
    preBuildScripts:
      - script: "mint run swiftgen"
        name: SwiftGen
    postCompileScripts:
      - script: "mint run swiftformat . --swiftversion 5.5"
        name: SwiftFormat
      - script: "mint run swiftlint"
        name: SwiftLint
  BookieAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: [BookieTests]
    dependencies:
      - target: BookieApp
    info:
      path: BookieTests/Info.plist
