name: Bookie
options:
  bundleIdPrefix: com.bookie
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "16.2"
packages:
  Fashion:
    url: https://github.com/vadymmarkov/Fashion.git
    version: 4.2.0
  Swinject:
    url: https://github.com/Swinject/Swinject.git
    version: 2.9.1
  CombineMoya:
    url: https://github.com/Moya/Moya
    version: 15.0.3
  Then:
    url: https://github.com/devxoul/Then
    version: 3.0.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    version: 5.7.1
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    version: 8.3.2
  SwifterSwift:
    url: https://github.com/SwifterSwift/SwifterSwift
    version: 7.0.0
  Reusable:
    url: https://github.com/AliSoftware/Reusable
    version: 4.1.2
  DifferenceKit:
    url: https://github.com/ra1028/DifferenceKit
    version: 1.3.0
  NVActivityIndicatorViewExtended:
    url: https://github.com/ninjaprox/NVActivityIndicatorView
    version: 5.2.0
  UICollectionViewLeftAlignedLayout:
    url: https://github.com/mokagio/UICollectionViewLeftAlignedLayout
    version: 1.1.0
  SwiftAlertView:
    url: https://github.com/dinhquan/SwiftAlertView
    version: 2.2.1
  OrderedCollections:
    url: https://github.com/apple/swift-collections
    version: 1.1.4
  JobInterviewAssignmentKit:
    url: https://github.com/RomanPodymov/JobInterviewAssignmentKit
    version: 0.0.1
  RealmSwift:
    url: https://github.com/realm/realm-swift.git
    version: 20.0.2
targets:
  BookieApp:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: application
    platform: iOS
    sources: [Bookie]
    dependencies:
      - package: Fashion
      - package: Swinject
      - package: CombineMoya
      - package: Then
      - package: SnapKit
      - package: Kingfisher
      - package: SwifterSwift
      - package: Reusable
      - package: DifferenceKit
      - package: NVActivityIndicatorViewExtended
      - package: UICollectionViewLeftAlignedLayout
      - package: SwiftAlertView
      - package: OrderedCollections
      - package: JobInterviewAssignmentKit
      - package: RealmSwift
        embed: true
    info:
      path: Bookie/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: YES
    preBuildScripts:
      - script: "/opt/homebrew/bin/mint run swiftgen"
        name: SwiftGen
    postCompileScripts:
      - script: "/opt/homebrew/bin/mint run swiftformat . --swiftversion 5.5"
        name: SwiftFormat
      - script: "/opt/homebrew/bin/mint run swiftlint"
        name: SwiftLint
  BookieAppTests:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: bundle.unit-test
    platform: iOS
    sources: [BookieTests]
    dependencies:
      - target: BookieApp
    info:
      path: BookieTests/Info.plist
